/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib_project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */

public class admin_page extends javax.swing.JFrame {

    /**
     * Creates new form admin_page
     */
    public admin_page() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigation_panel = new javax.swing.JPanel();
        btn_lib_reg = new javax.swing.JButton();
        btn_view_lib = new javax.swing.JButton();
        btn_remove_lib = new javax.swing.JButton();
        btn_admin_logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        update_lib_btn = new javax.swing.JButton();
        show_panel = new javax.swing.JPanel();
        welcome_admin_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lib_reg_panel = new javax.swing.JPanel();
        Lib_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Lib_email = new javax.swing.JTextField();
        Lib_pass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Lib_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Lib_contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_save_lib = new javax.swing.JButton();
        view_lib_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lib_table = new javax.swing.JTable();
        remove_lib_panel = new javax.swing.JPanel();
        id_textfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_lib_removed = new javax.swing.JButton();
        update_lib_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        update_table = new javax.swing.JTable();
        name_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pass_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mail_field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        add_field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        con_field = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lib_updatted_btn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navigation_panel.setBackground(new java.awt.Color(102, 102, 255));

        btn_lib_reg.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_lib_reg.setText("Librarian Registration");
        btn_lib_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lib_regActionPerformed(evt);
            }
        });

        btn_view_lib.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_view_lib.setText("View Librarian");
        btn_view_lib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_libActionPerformed(evt);
            }
        });

        btn_remove_lib.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_remove_lib.setText("Remove Librarian");
        btn_remove_lib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove_libActionPerformed(evt);
            }
        });

        btn_admin_logout.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_admin_logout.setText("Logout");
        btn_admin_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_logoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Admin Panel");

        update_lib_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        update_lib_btn.setText("Update Data");
        update_lib_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_lib_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigation_panelLayout = new javax.swing.GroupLayout(navigation_panel);
        navigation_panel.setLayout(navigation_panelLayout);
        navigation_panelLayout.setHorizontalGroup(
            navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigation_panelLayout.createSequentialGroup()
                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(navigation_panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, navigation_panelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_lib_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_admin_logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(navigation_panelLayout.createSequentialGroup()
                                .addGroup(navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_lib_reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_view_lib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_remove_lib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        navigation_panelLayout.setVerticalGroup(
            navigation_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigation_panelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btn_lib_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_view_lib, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update_lib_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_remove_lib, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_admin_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        show_panel.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Central College Library  Admin Panel");

        javax.swing.GroupLayout welcome_admin_panelLayout = new javax.swing.GroupLayout(welcome_admin_panel);
        welcome_admin_panel.setLayout(welcome_admin_panelLayout);
        welcome_admin_panelLayout.setHorizontalGroup(
            welcome_admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_admin_panelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        welcome_admin_panelLayout.setVerticalGroup(
            welcome_admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_admin_panelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        show_panel.add(welcome_admin_panel, "card2");

        lib_reg_panel.setBackground(new java.awt.Color(153, 153, 255));

        Lib_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name");

        Lib_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Lib_pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Email");

        Lib_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Address");

        Lib_contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Contact");

        btn_save_lib.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_save_lib.setText("Save");
        btn_save_lib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_libActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lib_reg_panelLayout = new javax.swing.GroupLayout(lib_reg_panel);
        lib_reg_panel.setLayout(lib_reg_panelLayout);
        lib_reg_panelLayout.setHorizontalGroup(
            lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lib_reg_panelLayout.createSequentialGroup()
                .addGroup(lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lib_reg_panelLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(36, 36, 36)
                        .addGroup(lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lib_contact, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(Lib_address)
                            .addComponent(Lib_pass)
                            .addComponent(Lib_email)
                            .addComponent(Lib_name)))
                    .addGroup(lib_reg_panelLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(btn_save_lib, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        lib_reg_panelLayout.setVerticalGroup(
            lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lib_reg_panelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lib_name, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lib_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lib_email, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lib_address, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(lib_reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lib_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btn_save_lib, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        show_panel.add(lib_reg_panel, "card2");

        lib_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lib_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "L_id", "L_name ", "L_password  ", "L_email", "L_address", "L_contact"
            }
        ));
        jScrollPane1.setViewportView(lib_table);

        javax.swing.GroupLayout view_lib_panelLayout = new javax.swing.GroupLayout(view_lib_panel);
        view_lib_panel.setLayout(view_lib_panelLayout);
        view_lib_panelLayout.setHorizontalGroup(
            view_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        view_lib_panelLayout.setVerticalGroup(
            view_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        show_panel.add(view_lib_panel, "card2");

        id_textfield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Enter ID ");

        btn_lib_removed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_lib_removed.setText("Remove");
        btn_lib_removed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lib_removedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout remove_lib_panelLayout = new javax.swing.GroupLayout(remove_lib_panel);
        remove_lib_panel.setLayout(remove_lib_panelLayout);
        remove_lib_panelLayout.setHorizontalGroup(
            remove_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, remove_lib_panelLayout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(remove_lib_panelLayout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(btn_lib_removed, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        remove_lib_panelLayout.setVerticalGroup(
            remove_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remove_lib_panelLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(remove_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(btn_lib_removed, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        show_panel.add(remove_lib_panel, "card2");

        update_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "L_id", "L_name", "L_pass", "L_email", "L_address", "L_contact"
            }
        ));
        update_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(update_table);

        name_field.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Name");

        pass_field.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Password");

        mail_field.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Email");

        add_field.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Address");

        con_field.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Contact");

        lib_updatted_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lib_updatted_btn.setText("Update");
        lib_updatted_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lib_updatted_btnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Please Select the Row");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("you want to Update");

        javax.swing.GroupLayout update_lib_panelLayout = new javax.swing.GroupLayout(update_lib_panel);
        update_lib_panel.setLayout(update_lib_panelLayout);
        update_lib_panelLayout.setHorizontalGroup(
            update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, update_lib_panelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(update_lib_panelLayout.createSequentialGroup()
                            .addGroup(update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel9)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name_field)
                                .addComponent(pass_field)
                                .addComponent(mail_field)
                                .addComponent(add_field)
                                .addComponent(con_field, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, update_lib_panelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lib_updatted_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50))
                        .addComponent(jLabel15))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        update_lib_panelLayout.setVerticalGroup(
            update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, update_lib_panelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(42, 42, 42)
                .addGroup(update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail_field, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(update_lib_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(73, 73, 73)
                .addComponent(lib_updatted_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        show_panel.add(update_lib_panel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigation_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigation_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(show_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_save_libActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_libActionPerformed
         String lib_name= Lib_name.getText().trim();
         String lib_pass=Lib_pass.getText().trim();
         String lib_email= Lib_email.getText().trim();
         String lib_add= Lib_address.getText().trim();
         String lib_contact= Lib_contact.getText().trim();
        
         
                         
                         try {  
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
             Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=lib_project;integratedSecurity=true");  
  
               Statement statement = connection.createStatement();  
               if (!(lib_name.isEmpty()) && !(lib_pass.isEmpty()) && !(lib_email.isEmpty()) && !(lib_add.isEmpty()) && !(lib_contact.isEmpty())){
statement.execute(" insert into librarian "  + " values ('"+lib_name+"', '"+lib_pass+"', '"+lib_email+"', '"+lib_add+"', '"+lib_contact+"')" );     
JOptionPane.showMessageDialog(admin_page.this, "Information Saved!" , "Success" , JOptionPane.INFORMATION_MESSAGE);
             Lib_name.setText("");
             Lib_pass.setText("");
             Lib_email.setText("");
             Lib_address.setText("");
             Lib_contact.setText("");
             
               }
               else{
                   JOptionPane.showMessageDialog(admin_page.this, "One or several data fields are missing!" , "Error" , JOptionPane.ERROR_MESSAGE);
               }

         } catch (Exception e) {  
             
             e.printStackTrace();  
         }  
    }//GEN-LAST:event_btn_save_libActionPerformed

    private void btn_lib_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lib_regActionPerformed
        show_panel.removeAll();
        show_panel.repaint();
        show_panel.revalidate();
        
        show_panel.add(lib_reg_panel);
        show_panel.repaint();
        show_panel.revalidate();
        
             name_field.setText("");
             pass_field.setText("");
             mail_field.setText("");
             add_field.setText("");
             con_field.setText("");
    }//GEN-LAST:event_btn_lib_regActionPerformed

    private void btn_view_libActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_libActionPerformed
        show_panel.removeAll();
        show_panel.repaint();
        show_panel.revalidate();
        
        show_panel.add(view_lib_panel);
        show_panel.repaint();
        show_panel.revalidate();
        
             name_field.setText("");
             pass_field.setText("");
             mail_field.setText("");
             add_field.setText("");
             con_field.setText("");
        
        try {  
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
             Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=lib_project;integratedSecurity=true");  
   
               Statement statement = connection.createStatement();  
               
             ResultSet rs = statement.executeQuery("SELECT  * FROM librarian");  
             ResultSetMetaData  rsmetadata = rs.getMetaData(); 
              int  columns = rsmetadata.getColumnCount();   
              DefaultTableModel dtm = new DefaultTableModel(); 
              Vector columns_name=new Vector();
              Vector data_rows=new Vector();
              for(int  i= 1; i < columns+1; i++)  
                {             
                        columns_name.addElement (rsmetadata.getColumnLabel(i));  
                }                 
              
              dtm.setColumnIdentifiers(columns_name);
                   while (rs.next())  
           {  
               data_rows = new Vector(); 
               for (int j = 1; j <columns+1; j++)  
               {  
                   data_rows.addElement(rs.getString(j)) ;
               }  
               dtm.addRow(data_rows);  
               
       }   
          lib_table.setModel(dtm); 
             
         } catch (Exception e) {  
             e.printStackTrace();  
         }  
        
    }//GEN-LAST:event_btn_view_libActionPerformed

    private void btn_admin_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_logoutActionPerformed
               new front_page().setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_btn_admin_logoutActionPerformed

    private void btn_remove_libActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove_libActionPerformed
        show_panel.removeAll();
        show_panel.repaint();
        show_panel.revalidate();
        
        show_panel.add(remove_lib_panel);
        show_panel.repaint();
        show_panel.revalidate();
        
             name_field.setText("");
             pass_field.setText("");
             mail_field.setText("");
             add_field.setText("");
             con_field.setText("");
    }//GEN-LAST:event_btn_remove_libActionPerformed

    private void btn_lib_removedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lib_removedActionPerformed
           
        String id = id_textfield.getText().trim();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=lib_project;integratedSecurity=true"); 
            Statement statement = connection.createStatement(); 
            
            if (!id.isEmpty()){
            int deleted = statement.executeUpdate("delete from librarian where L_id= '"+id+"'");
            if (deleted==0){
                JOptionPane.showMessageDialog(admin_page.this, "Nothing to delete!" , "Sorry" , JOptionPane.INFORMATION_MESSAGE);
                id_textfield.setText("");
                return;
            }
            else {
            JOptionPane.showMessageDialog(admin_page.this, "Removed!" , "Success" , JOptionPane.INFORMATION_MESSAGE);
            id_textfield.setText("");
            }

            }
            else{
                JOptionPane.showMessageDialog(admin_page.this, "Please Enter ID!" , "Error" , JOptionPane.ERROR_MESSAGE);
            }
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_lib_removedActionPerformed

    private void update_lib_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_lib_btnActionPerformed
        show_panel.removeAll();
        show_panel.repaint();
        show_panel.revalidate();
        
        show_panel.add(update_lib_panel);
        show_panel.repaint();
        show_panel.revalidate();
        try {
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=lib_project;integratedSecurity=true"); 
            Statement statement = connection.createStatement();  
               
             ResultSet rs = statement.executeQuery("SELECT  * FROM librarian");  
             ResultSetMetaData  rsmetadata = rs.getMetaData(); 
              int  columns = rsmetadata.getColumnCount();   
              DefaultTableModel dtm = new DefaultTableModel(); 
              Vector columns_name=new Vector();
              Vector data_rows=new Vector();
              for(int  i= 1; i < columns+1; i++)  
                {             
                        columns_name.addElement (rsmetadata.getColumnLabel(i));  
                }                 
              
              dtm.setColumnIdentifiers(columns_name);
                   while (rs.next())  
           {  
               data_rows = new Vector(); 
               for (int j = 1; j <columns+1; j++)  
               {  
                   data_rows.addElement(rs.getString(j)) ;
               }  
               dtm.addRow(data_rows);  
               
       }   
          update_table.setModel(dtm);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_update_lib_btnActionPerformed

    private void lib_updatted_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lib_updatted_btnActionPerformed
        String name = name_field.getText().trim();
        String pass = pass_field.getText().trim();
        String mail = mail_field.getText().trim();
        String add = add_field.getText().trim();
        String con = con_field.getText().trim();
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=lib_project;integratedSecurity=true"); 
            
            if ((name.isEmpty()) || (pass.isEmpty()) || (mail.isEmpty()) || (add.isEmpty()) || (con.isEmpty())) {
                JOptionPane.showMessageDialog(admin_page.this, "Please Enter Data!" , "Error" , JOptionPane.ERROR_MESSAGE);
            } else{
                int row = update_table.getSelectedRow(); 
            String value = (update_table.getModel().getValueAt(row, 0).toString());
            String query = "update librarian set L_name = '"+name+"', L_password = '"+pass+"', L_email = '"+mail+"', L_address = '"+add+"', L_contact = '"+con+"' where L_id = '"+value+"'";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.executeUpdate();
          JOptionPane.showMessageDialog(admin_page.this, "Updated!" , "Success" , JOptionPane.INFORMATION_MESSAGE); 
              name_field.setText("");
             pass_field.setText("");
             mail_field.setText("");
             add_field.setText("");
             con_field.setText("");
             
             //refreshing table
             Statement statement = connection.createStatement();  
             ResultSet rs = statement.executeQuery("SELECT  * FROM librarian");  
             ResultSetMetaData  rsmetadata = rs.getMetaData(); 
              int  columns = rsmetadata.getColumnCount();   
              DefaultTableModel dtm = new DefaultTableModel(); 
              Vector columns_name=new Vector();
              Vector data_rows=new Vector();
              for(int  i= 1; i < columns+1; i++)  
                {             
                        columns_name.addElement (rsmetadata.getColumnLabel(i));  
                }                 
              
              dtm.setColumnIdentifiers(columns_name);
                   while (rs.next())  
           {  
               data_rows = new Vector(); 
               for (int j = 1; j <columns+1; j++)  
               {  
                   data_rows.addElement(rs.getString(j)) ;
               }  
               dtm.addRow(data_rows);  
       }   
          update_table.setModel(dtm);
            }         
        } catch (Exception e) {
        }
    }//GEN-LAST:event_lib_updatted_btnActionPerformed

    private void update_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_tableMouseClicked
        // TODO add your handling code here:
        int selectedRow = update_table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)update_table.getModel();
        name_field.setText(model.getValueAt(selectedRow, 1).toString());
        pass_field.setText(model.getValueAt(selectedRow, 2).toString());
        mail_field.setText(model.getValueAt(selectedRow, 3).toString());
        add_field.setText(model.getValueAt(selectedRow, 4).toString());
        con_field.setText(model.getValueAt(selectedRow, 5).toString());
        
    }//GEN-LAST:event_update_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lib_address;
    private javax.swing.JTextField Lib_contact;
    private javax.swing.JTextField Lib_email;
    private javax.swing.JTextField Lib_name;
    private javax.swing.JPasswordField Lib_pass;
    private javax.swing.JTextField add_field;
    private javax.swing.JButton btn_admin_logout;
    private javax.swing.JButton btn_lib_reg;
    private javax.swing.JButton btn_lib_removed;
    private javax.swing.JButton btn_remove_lib;
    private javax.swing.JButton btn_save_lib;
    private javax.swing.JButton btn_view_lib;
    private javax.swing.JTextField con_field;
    private javax.swing.JTextField id_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lib_reg_panel;
    private javax.swing.JTable lib_table;
    private javax.swing.JButton lib_updatted_btn;
    private javax.swing.JTextField mail_field;
    private javax.swing.JTextField name_field;
    private javax.swing.JPanel navigation_panel;
    private javax.swing.JTextField pass_field;
    private javax.swing.JPanel remove_lib_panel;
    private javax.swing.JPanel show_panel;
    private javax.swing.JButton update_lib_btn;
    private javax.swing.JPanel update_lib_panel;
    private javax.swing.JTable update_table;
    private javax.swing.JPanel view_lib_panel;
    private javax.swing.JPanel welcome_admin_panel;
    // End of variables declaration//GEN-END:variables
}
